export const clamp01 = (value) => Math.min(1, Math.max(0, value));

export const BACKGROUND_SETTINGS = {
  dprCap: 2,
  pageHeightCheckIntervalMs: 350,
  heroField: {
    maxHeight: 1600,
  },
  heroCutout: {
    // Keeps dots softer behind the hero title/content zone.
    halfWidthRatio: 0.34,
    halfHeightRatio: 0.3,
    centerYRatio: 0.32,
    squareness: 3.2,
    fadeInnerRatio: 0.42,
    fadeOuterRatio: 1,
    minVisibility: 0.06,
  },
  normal: {
    gridSpacing: 24,
    pointSize: 1.25,
    baseAlpha: 0.28,
    visibleMargin: 140,
    returnStrength: 0.018,
    damping: 0.9,
    maxSpeed: 5,
    pointerRadius: 160,
    pointerForce: 0.62,
    heatDecay: 0.94,
    scanDecay: 0.88,
    enableNavPulse: true,
    navPulseStep: 14,
    navPulseBand: 68,
    navPulseForce: 0.44,
    enableAura: true,
    auraRadius: 180,
    auraPull: 0.01,
    auraWobble: 0.25,
  },
  reduced: {
    gridSpacing: 34,
    pointSize: 1.15,
    baseAlpha: 0.18,
    visibleMargin: 90,
    returnStrength: 0.024,
    damping: 0.92,
    maxSpeed: 3,
    pointerRadius: 0,
    pointerForce: 0,
    heatDecay: 0.9,
    scanDecay: 0.85,
    enableNavPulse: false,
    navPulseStep: 0,
    navPulseBand: 0,
    navPulseForce: 0,
    enableAura: false,
    auraRadius: 0,
    auraPull: 0,
    auraWobble: 0,
  },
};
